### ISSUE TITLE
As a developer i would like to have the ROS API for packml as a seperate repo

### ISSUE THREAD

**Issue by AustinDeric** [plusone-robotics/packml_msgs#1]
# Problem
In order to provide a ROS API interface to a packml state machine for both the topics and services of [packml](https://github.com/ros-industrial-consortium/packml) i have to build the entire packml repo which contains unrelated code for my purposes. The entire repo contains dependencies that are not necessary when creating a ROS Service client or server: 
- https://github.com/ros-industrial-consortium/packml/blob/8e22ca40812379fbcabed96ca148a0e19652b6e8/packml_sm/package.xml#L12
- https://github.com/ros-industrial-consortium/packml/blob/8e22ca40812379fbcabed96ca148a0e19652b6e8/packml_gui/package.xml#L14
- https://github.com/ros-industrial-consortium/packml/blob/indigo-devel/packml_ros/package.xml

# Details
It is best practice to separate the ROS API package which in this case is [packml_msgs](https://github.com/ros-industrial-consortium/packml/tree/indigo-devel/packml_msgs)

**Comment by gavanderhoorn** [comment]
I realise this is pedantic, but I believe something is not entirely correct here.

The problem is described as:

> In order to provide a ROS API interface to a packml state machine for both the topics and services of packml i have to build the entire packml repo which contains unrelated code for my purposes.

This is simply not true, and additionally, creating a separate repository is only one of the possible ways to to address this, but it's presented as the only one.

---

Using/building just `packml_msgs` is perfectly possible: clone the packml repository and just ignore the rest of the pkgs (catkin profile blacklist, `rm -rf` unwanted pkgs or even a simple `CATKIN_IGNORE`).

If that is too much work / inconvenient: release `ros-industrial-consortium/packml`. That would immediately make it possible to only install `ros-$distro-packml-msg`.

It's even possible to release a subset of packages from a repository with Bloom (by using a `$distro.ignored` file in the release repository).

That would not require any changes to anything, and avoids #3 (which of course will be resolved once `packml_msgs` is removed from `ros-industrial-consortium/packml`, but the point is: the problem could have been avoided completely in the first place).

**Comment by 130s** [comment]
> If that is too much work / inconvenient: release `ros-industrial-consortium/packml`. That would immediately make it possible to only install `ros-$distro-packml-msg`.

Just FYI I'm offering assistance to make a (binary) release and started https://github.com/ros-industrial-consortium/packml/pull/52
